### ISSUE TITLE
Please help me.

### ISSUE THREAD

**Issue by Zhu-Yiting** [Russel88/DOC#5]
Hi, recently I was trying to use your code to do Dissimilarity Overlap Curve analysis, however I had some difficulties.
  Here is my problem. When I run the code sentence " Silk_16S_DOC_results <- DOC(ASV_Silk_16S, R = 1000) "  to get results just like "results <- DOC(otu)", it will show error like                                                                                                                                                     
 "Running bootstraps
  |                                                                                                                  |   0%Error in { : 
  task 1 failed - "function 'chm_factor_ldetL2' not provided by package 'Matrix'"
In addition: There were 50 or more warnings (use warnings() to see the first 50)". 
And I have already installed Matrix package , the version is 1.7-1. I guess that maybe wrong version of Matrix package leads to my error .But I don't know which version is the correct one. Or maybe there is something else that leads to my error.
  I will sincerely appreciate it if you can  help me to solve this problem. Thank you very much. Wish you have a good day!

**Comment by Russel88** [comment]
Yes, it looks like a version problem. This package (DOC) was developed several years ago and I haven't updated it to follow development of dependencies. It might help to install Matrix version <= 1.6.3

**Comment by Zhu-Yiting** [comment]
Thank you for your timely answer! I tried Matrix version 1.6.3 and it worked very well. Now I can continue my study. I just can't tell you how excited I was when the error not showed as usual  ! And I want to thank you again for helping me solve this problem. Wish you have a good day !
